### ISSUE TITLE
The Renderer Has Issues with xamarin Forms 2+

### ISSUE THREAD

**Issue by tickerman** [CrossGeeks/CustomNavigationBarSample#1]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'NavigationPageRenderer.NavigationPageRenderer()' is obsolete: 'This constructor is obsolete as of version 2.5. Please use NavigationPageRenderer(Context) instead.'	CustomNavigationBarSample.Android	~\CustomNavigationBarSample.Android\Renderers\CustomNavigationPageRenderer.cs	30	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'View.SetBackgroundDrawable(Drawable)' is obsolete: 'deprecated'	CustomNavigationBarSample.Android	~\CustomNavigationBarSample.Android\Renderers\CustomNavigationPageRenderer.cs	451	Active

and more ...

**Comment by rdelrosario** [comment]
Done. Just upgraded the sample. Thanks for reporting this.
