### ISSUE TITLE
Center alignment is not centered

### ISSUE THREAD

**Issue by vhugogarcia** [CrossGeeks/CustomNavigationBarSample#3]
Hello @rdelrosario ,

I think I found a bug while rendering the text. The alignment is not correct when centering on modal pages with a button on the toolbar. 

I'm attaching an screenshot for reference: https://s14.postimg.org/njv2pthgx/Screen_Shot_2018-03-11_at_12.18.53_PM.png

I think it is centering based on the free after toolbar buttons are rendered, however, that makes it look weird aligned as you can see on the screenshot above.

Regards,
Victor

**Comment by rdelrosario** [comment]
mm that might be fixed when calculating the center position by subtracting the with of the bar button items on iOS. 

This is just happening on iOS?

**Comment by vhugogarcia** [comment]
This was just happening on iOS, you are right. On Android, I did not test it due Android natively goes to the left position.

**Comment by chrismerron** [comment]
I'm having the same issue on iOS. Hiding the back button using SetHasBackButton doesn't appear to resolve the issue either.

**Comment by ali-h2010** [comment]
@rdelrosario , I found out that only if there are no toolbar icons or if there is one Icon on the left and the right that the title will be centered.

**Comment by ali-h2010** [comment]
I did more testing and apparently if the title is too long it will shit to the right for some reason. 
I think the cause is that, the title is set after the calculation of the center is made.

**Comment by onurhazar** [comment]
Hello, custom nav bar is great! Thanks! Is there a solution for this alignment glitch for iOS?
